name: Docs

on:
    pull_request_target:
    push:
        branches:
            - '[0-9]+.[0-9]+'

permissions:
    contents: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - name: Output infos
              run: |
                  echo "${{ github.event.pull_request.merge_commit_sha }}"
                  echo "${{ github.event.pull_request.head.sha }}"

            - name: Checkout project
              uses: actions/checkout@v4
              with:
                  ref: "${{ github.event.pull_request.head.sha }}"

            - name: Git infos
              run: |
                  git rev-parse HEAD
                  git branch --show-current

            - uses: actions/setup-python@v5

            - name: Install dependencies
              run: |
                  pip install -r docs/requirements.txt

            - name: List dependencies
              run: |
                  pip list

            - name: Sphinx build
              run: |
                  sphinx-build docs docs/_build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/0.6' }}
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/_build/
                  force_orphan: true
